/**************************************************************
* contain all characters
* BOX_NUM0809[][9];ASC0811[][11];ICON1616[][32];LOGO16080[]
***************************************************************/

#ifndef _DRI_LCDCHARACTERS_H_
#define _DRI_LCDCHARACTERS_H_  1

extern __flash  unsigned char BOX_NUM0809[][9];
extern __flash  unsigned char ASC0811[][11];
extern __flash  unsigned char ICON1616[][32];
extern __flash  unsigned char LOGO16080[];


#endif